require_relative 'tests/Test'
require_relative 'tests/OCMlaunchECase'
require_relative 'tests/OCMwelcome'
require_relative 'tests/OCMcorrectProgramName'
require_relative 'tests/OCMcaseNumbersDisplayed'
require_relative 'tests/VEFbuttonExists'
require_relative 'tests/VEFbuttonClick'
require_relative 'tests/VEFbuttonClickAfterSessionTimeOut'
